import { GoogleGenerativeAI } from "@google/generative-ai";

export const generateAIReport = async (apiKey, kpis, insights) => {
    if (!apiKey) throw new Error("API Key is missing");

    const cleanKey = apiKey.trim().replace(/["']/g, '');

    // Dynamic Model Selection:
    // 1. Try to list models that the API Key has access to.
    // 2. Pick the first one that supports 'generateContent'.
    // 3. Use that model for the generation request.

    let model = "gemini-1.5-flash"; // Fallback default
    try {
        const models = await listAvailableModels(apiKey);
        // Find a model that supports generation and preferably is "flash" or "pro"
        const bestModel = models.find(m =>
            m.supportedGenerationMethods &&
            m.supportedGenerationMethods.includes("generateContent") &&
            (m.name.includes("flash") || m.name.includes("pro"))
        );

        if (bestModel) {
            // The API returns names like "models/gemini-1.5-flash". 
            // The generateContent URL expects just the name part usually, OR the full resource.
            // Let's use the name exactly as returned by the API but strip 'models/' if the URL structure duplicates it.
            // URL structure: v1beta/{model_name}:generateContent. 
            // IF model_name is "models/gemini...", then v1beta/models/gemini... is correct.
            model = bestModel.name;
            console.log("Auto-negotiated AI Model:", model);
        }
    } catch (e) {
        console.warn("Model auto-detection failed, using fallback:", e);
    }

    // If the model name already starts with 'models/', don't add it again in the URL if we construct it manually.
    // But the standard endpoint is /v1beta/models/{model}:generateContent
    // If 'model' is 'models/gemini-pro', then we should just use /v1beta/{model}:generateContent

    const baseUrl = "https://generativelanguage.googleapis.com/v1beta";
    const finalModelName = model.startsWith("models/") ? model : `models/${model}`;
    const url = `${baseUrl}/${finalModelName}:generateContent?key=${cleanKey}`;

    const promptText = `
    Act as a Senior Business Analyst for a company using WhatsApp for sales.
    Analyze the following KPI data and provide a strategic report.
    
    DATA:
    - Total Leads: ${kpis.totalLeads}
    - Total Messages: ${kpis.totalMsgs}
    - Leads Captured (Interest): ${kpis.leadsCaptured}
    - Ghosting Rate (Lost at Closing): ${kpis.ghostingRate}%
    - High Value Leads (Score > 35): ${kpis.highValueCount}
    - Response Speed Critical (> 4h): ${(kpis.responseDistribution?.find(d => d.label.includes('> 4')) || { count: 0 }).count}
    - Night Queries (8PM-7AM): ${kpis.nightQueries}
    
    CURRENT INSIGHTS DETECTED:
    ${insights.map(i => `- ${i.title}: ${i.issue}`).join('\n')}
    
    OUTPUT FORMAT (Markdown):
    ## 1. Diagnóstico Ejecutivo
    [Brief summary of the current situation, tone: professional and direct]
    
    ## 2. Oportunidades de Ingresos (Proyección)
    [Calculate potential lost revenue based on Ghosting Rate and High Value Leads. Assume High Value Lead = $500 USD avg value.]
    
    ## 3. Acciones Inmediatas (Prioridad Alta)
    - [Action 1]
    - [Action 2]
    - [Action 3]
    
    ## 4. Estrategia de Contenido & Scripts
    [Suggest 1 specific WhatsApp script to recover 'Ghosted' leads based on the data]
    `;

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: promptText }]
                }]
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error?.message || `API Error: ${response.status}`);
        }

        if (data.candidates && data.candidates.length > 0) {
            return data.candidates[0].content.parts[0].text;
        } else {
            throw new Error("No content generated by AI.");
        }

    } catch (error) {
        console.error("Error generating AI report:", error);
        throw error;
    }
};

export const listAvailableModels = async (apiKey) => {
    if (!apiKey) throw new Error("API Key is missing");
    const cleanKey = apiKey.trim().replace(/["']/g, '');

    // Direct REST call to bypass SDK issues if any
    try {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${cleanKey}`);
        const data = await response.json();

        if (data.error) {
            throw new Error(data.error.message);
        }

        return data.models || [];
    } catch (error) {
        console.error("Error listing models:", error);
        throw error;
    }
};
